services:
  sqlserver:
    container_name: article-db-demonstration
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongestPass@word"
      MSSQL_PID: Developer
    ports:
      - 1433:1433
  
  api:
    container_name: article-api-demonstration
    build: 
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 8080:8080
    environment:
      - ConnectionStrings__DemoDbConnectionString=

  migrations:
    container_name: article-migrations-demonstration
    build:
      context: .
      dockerfile: migrations.Dockerfile
    environment:
      - ConnectionStrings__DemoDbConnectionString=